// <auto-generated />
using M_N_update.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M_N_update.Migrations
{
    [DbContext(typeof(M_N_updateDB))]
    [Migration("20210628220522_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryLesson", b =>
                {
                    b.Property<int>("CategoriesListID")
                        .HasColumnType("int");

                    b.Property<int>("LessonListID")
                        .HasColumnType("int");

                    b.HasKey("CategoriesListID", "LessonListID");

                    b.HasIndex("LessonListID");

                    b.ToTable("CategoryLesson");

                    b.HasData(
                        new
                        {
                            CategoriesListID = 1,
                            LessonListID = 1
                        },
                        new
                        {
                            CategoriesListID = 1,
                            LessonListID = 2
                        },
                        new
                        {
                            CategoriesListID = 2,
                            LessonListID = 1
                        },
                        new
                        {
                            CategoriesListID = 3,
                            LessonListID = 2
                        },
                        new
                        {
                            CategoriesListID = 4,
                            LessonListID = 3
                        });
                });

            modelBuilder.Entity("M_N_update.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "A"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "B"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "C"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "D"
                        });
                });

            modelBuilder.Entity("M_N_update.Models.Lesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "description First Lesson",
                            Nome = "name First Lesson"
                        },
                        new
                        {
                            ID = 2,
                            Description = "description Second Lesson",
                            Nome = "name Second Lesson"
                        },
                        new
                        {
                            ID = 3,
                            Description = "description Third Lesson ",
                            Nome = "name Third Lesson"
                        });
                });

            modelBuilder.Entity("CategoryLesson", b =>
                {
                    b.HasOne("M_N_update.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M_N_update.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
